In [17]:
%matplotlib inline
import pandas as pd
import numpy as np
from urllib import request

In [18]:
url = "https://www.nbp.pl/systemfinansowy/zrodlo-roz.xlsx"

Download data

In [19]:
path = '../data/loans.xlsx'
# Download remote and save locally
data = request.urlretrieve(url, path)

Read data into dataframe

In [20]:
df = pd.read_excel(path,sheet_name=0)

In [21]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78
0,NaN,"Kwartał, którego dotyczą pytania o przewidywan...",I.2004,II.2004,III.2004,IV.2004,I.2005,II.2005,III.2005,IV.2005,...,IV.2020,I.2021,II.2021,III.2021,IV.2021,I.2022,II.2022,III.2022,IV.2022,I.2023
1,NaN,"Kwartał, którego dotyczą pytania o stan (S)",IV.2003,I.2004,II.2004,III.2004,IV.2004,I.2005,II.2005,III.2005,...,III.2020,IV.2020,I.2021,II.2021,III.2021,IV.2021,I.2022,II.2022,III.2022,IV.2022
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Sektor przedsiębiorstw:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,NaN,Kredyty konsumpcyjne,0.297676,0.056642,0.238588,0.304885,0.167232,0.074552,0.000665,0.009959,...,0.143132,-0.032819,0.093204,0.143786,0.029781,-0.057215,-0.027605,-0.209356,-0.151159,-0.266991
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,NaN,Pyt. 17: Popyt na kredyt (P),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,Kredyty mieszkaniowe,0.332,0.709814,0.233391,0.533731,0.303307,0.533503,0.197923,0.501198,...,0.208412,0.334997,0.388755,0.035481,-0.068727,-0.369343,-0.736668,-0.574617,-0.298529,0.019507
131,NaN,Kredyty konsumpcyjne,0.364543,0.577346,0.358941,0.458583,0.365168,0.482928,0.376397,0.388016,...,0.229485,0.082983,0.152704,0.231994,0.241036,-0.057782,0.029479,-0.32065,-0.333463,-0.121659

In [22]:
#pick row nr 3 as columns names
cols = df.iloc[1:2, 1:110].values
#slice the dataframe
df = df.iloc[108:115, 1:79]
#and change its column names
df.columns = cols[0]
df.rename(columns={'Kwartał, którego dotyczą pytania o stan (S)':'parameters'})

,parameters,IV.2003,I.2004,II.2004,III.2004,IV.2004,I.2005,II.2005,III.2005,IV.2005,...,III.2020,IV.2020,I.2021,II.2021,III.2021,IV.2021,I.2022,II.2022,III.2022,IV.2022
108,Prognozy odnośnie sytuacji na rynku mieszkaniowym,0.431139,0.591632,0.809363,0.230082,0.266053,0.482618,0.649565,0.418226,0.044749,...,0.044324,0.05951,0.322786,0.59181,0.139255,-0.157503,-0.282905,-0.473571,-0.549571,-0.079312
109,Zmiany w wydatkach konsumpcyjnych,-0.04644,0.073255,0.083417,-0.038803,0.0079,0.393063,0.190305,0.202078,0,...,-0.079475,0.053786,0.005301,0.124624,-0.075723,-0.145476,-0.466923,-0.508385,-0.440012,-0.344548
110,Wykorzystanie alternatywnych źródeł finansowania,-0.046538,0.032498,0.057612,0.027648,0.013183,-0.22202,0.465328,0.190659,0.035151,...,0.030216,-0.020128,0.077619,0.018993,-0.088323,-0.035757,-0.075526,-0.133011,-0.119988,-0.09288
111,Zmiana sytuacji ekonomicznej gospodarstw domowych,0.03626,0.304602,0.149892,0.224047,0.21763,0.4379,0.420135,0.382946,0.037613,...,-0.155712,-0.092097,0.014843,0.119152,0.117132,-0.144237,-0.495623,-0.56463,-0.638404,-0.476696
112,Zmiana warunków udzielania kredytów mieszkanio...,0.28006,0.339085,0.12056,0.262768,0.285014,0.45413,0.493698,0.226447,0.080908,...,-0.076467,0.045986,0.185134,0.151301,-0.043778,-0.107572,-0.092373,-0.411703,-0.223493,-0.133135
113,Zmiana kryteriów udzielania kredytów mieszkani...,0.236574,-0.150207,0.057872,0.083559,0.02516,0.230083,0.262385,0.207864,0.007323,...,-0.004998,0.048242,0.153981,0.187671,-0.139737,-0.019827,-0.113838,-0.489879,-0.184307,-0.133135
114,Inne czynniki,-0.036145,0.092446,0.178504,-0.134876,0.135558,0.048915,0.080822,0,0.16597,...,0.151612,-0.153898,-0.022492,0.106106,0.042418,-0.173835,-0.567222,-0.180321,-0.396302,-0.097345

Lets transpose the table so the dates are in rows

In [23]:
df = df.transpose()
df

,108,109,110,111,112,113,114
"Kwartał, którego dotyczą pytania o stan (S)",Prognozy odnośnie sytuacji na rynku mieszkaniowym,Zmiany w wydatkach konsumpcyjnych,Wykorzystanie alternatywnych źródeł finansowania,Zmiana sytuacji ekonomicznej gospodarstw domowych,Zmiana warunków udzielania kredytów mieszkanio...,Zmiana kryteriów udzielania kredytów mieszkani...,Inne czynniki
IV.2003,0.431139,-0.04644,-0.046538,0.03626,0.28006,0.236574,-0.036145
I.2004,0.591632,0.073255,0.032498,0.304602,0.339085,-0.150207,0.092446
II.2004,0.809363,0.083417,0.057612,0.149892,0.12056,0.057872,0.178504
III.2004,0.230082,-0.038803,0.027648,0.224047,0.262768,0.083559,-0.134876
...,...,...,...,...,...,...,...
IV.2021,-0.157503,-0.145476,-0.035757,-0.144237,-0.107572,-0.019827,-0.173835
I.2022,-0.282905,-0.466923,-0.075526,-0.495623,-0.092373,-0.113838,-0.567222
II.2022,-0.473571,-0.508385,-0.133011,-0.56463,-0.411703,-0.489879,-0.180321
III.2022,-0.549571,-0.440012,-0.119988,-0.638404,-0.223493,-0.184307,-0.396302
IV.2022,-0.079312,-0.344548,-0.09288,-0.476696,-0.133135,-0.133135,-0.097345

Rename firts fow with columns name

In [24]:
df.columns = df.iloc[0]

Remove first row

In [25]:
df = df[1:]

In [26]:
df

"Kwartał, którego dotyczą pytania o stan (S)",Prognozy odnośnie sytuacji na rynku mieszkaniowym,Zmiany w wydatkach konsumpcyjnych,Wykorzystanie alternatywnych źródeł finansowania,Zmiana sytuacji ekonomicznej gospodarstw domowych,Zmiana warunków udzielania kredytów mieszkaniowych,Zmiana kryteriów udzielania kredytów mieszkaniowych,Inne czynniki
IV.2003,0.431139,-0.04644,-0.046538,0.03626,0.28006,0.236574,-0.036145
I.2004,0.591632,0.073255,0.032498,0.304602,0.339085,-0.150207,0.092446
II.2004,0.809363,0.083417,0.057612,0.149892,0.12056,0.057872,0.178504
III.2004,0.230082,-0.038803,0.027648,0.224047,0.262768,0.083559,-0.134876
IV.2004,0.266053,0.0079,0.013183,0.21763,0.285014,0.02516,0.135558
...,...,...,...,...,...,...,...
IV.2021,-0.157503,-0.145476,-0.035757,-0.144237,-0.107572,-0.019827,-0.173835
I.2022,-0.282905,-0.466923,-0.075526,-0.495623,-0.092373,-0.113838,-0.567222
II.2022,-0.473571,-0.508385,-0.133011,-0.56463,-0.411703,-0.489879,-0.180321
III.2022,-0.549571,-0.440012,-0.119988,-0.638404,-0.223493,-0.184307,-0.396302
IV.2022,-0.079312,-0.344548,-0.09288,-0.476696,-0.133135,-0.133135,-0.097345

Lets work with data type in columns

In [27]:
#reset index, quarter will be new column
df = df.reset_index()
df.columns = ['Quarter', 'Loan_forcast', 'Changes_expenses', 'Alt_finansing', 'Change_economy', 'Change_rules', 'Change_criteria', 'Others']

#change type of all the columns with float type
cols = df.columns
df[cols[1:]] = df[cols[1:]].astype(float)

In [28]:
#change date columns to datetime
dates = df['Quarter'].to_list()
new_dates = []
for date in dates:
    q,y = date.split('.')
    if q == 'I': q = 'Q1'
    if q == 'II': q = 'Q2'
    if q == 'III': q = 'Q3'
    if q == 'IV': q = 'Q4'
    new_dates.append(y + '-' + q)
new_dates

#update dates and change data type
df['Quarter'] = new_dates
df['Date'] = pd.to_datetime(df['Quarter'])

#delate Quarter column
df = df.drop('Quarter', axis=1)

df.dtypes

Loan_forcast               float64
Changes_expenses           float64
Alt_finansing              float64
Change_economy             float64
Change_rules               float64
Change_criteria            float64
Others                     float64
Date                datetime64[ns]
dtype: object

In [29]:
%store df
df

Stored 'df' (DataFrame)

,Loan_forcast,Changes_expenses,Alt_finansing,Change_economy,Change_rules,Change_criteria,Others,Date
0,0.431139,-0.046440,-0.046538,0.036260,0.280060,0.236574,-0.036145,2003-10-01
1,0.591632,0.073255,0.032498,0.304602,0.339085,-0.150207,0.092446,2004-01-01
2,0.809363,0.083417,0.057612,0.149892,0.120560,0.057872,0.178504,2004-04-01
3,0.230082,-0.038803,0.027648,0.224047,0.262768,0.083559,-0.134876,2004-07-01
4,0.266053,0.007900,0.013183,0.217630,0.285014,0.025160,0.135558,2004-10-01
...,...,...,...,...,...,...,...,...
72,-0.157503,-0.145476,-0.035757,-0.144237,-0.107572,-0.019827,-0.173835,2021-10-01
73,-0.282905,-0.466923,-0.075526,-0.495623,-0.092373,-0.113838,-0.567222,2022-01-01
74,-0.473571,-0.508385,-0.133011,-0.564630,-0.411703,-0.489879,-0.180321,2022-04-01
75,-0.549571,-0.440012,-0.119988,-0.638404,-0.223493,-0.184307,-0.396302,2022-07-01
76,-0.079312,-0.344548,-0.092880,-0.476696,-0.133135,-0.133135,-0.097345,2022-10-01

One plot for better understending of data

In [30]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.lineplot(df, x='Date', y='Forcast')
sns.lineplot(df, x='Date', y='Changes_expenses')
sns.lineplot(df, x='Date', y='Change_criteria')
plt.show()

ValueError: Could not interpret value `Forcast` for parameter `y`

In [ ]:
df.describe()

,Forcast,Changes_expenses,Alt_finansing,Change_economy,Change_rules,Change_criteria,Others
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,0.075847,-0.019216,-0.020404,-0.014088,0.002265,-0.037427,0.017414
std,0.270920,0.132003,0.084971,0.204330,0.189201,0.159317,0.169385
min,-0.684408,-0.508385,-0.222020,-0.638404,-0.700183,-0.635448,-0.567222
25%,-0.051074,-0.042853,-0.050724,-0.092097,-0.091528,-0.059210,-0.025768
50%,0.051655,0.000000,-0.013643,0.005906,0.000000,-0.004998,0.027534
75%,0.190870,0.005301,0.010447,0.062878,0.083192,0.044362,0.100889
max,0.809363,0.393063,0.465328,0.437900,0.493698,0.262385,0.357803

In [ ]:
df.isnull().sum()

Forcast             0
Changes_expenses    0
Alt_finansing       0
Change_economy      0
Change_rules        0
Change_criteria     0
Others              0
Date                0
dtype: int64